Crud - fix all issues
galuhest/item-crud pull request #9
Opened 2018-07-04 07:20 UTC by galuhest

2018-07-04 10:02 UTC, yunusbahari requested changes

2018-07-04 10:02 UTC, yunusbahari commented on spec/item/crud_spec.rb
> +		status, id = createUser("item N")
masih 2 tab

2018-07-04 10:02 UTC, ryusan commented on spec/spec_helper.rb
> +  def createUser(name)
ini ada konvensi juga kalau ruby itu pakai `snake_case` bukan `camelCase` untuk penamaan method,
untuk penamaan class/module sudah benar

2018-07-04 10:34 UTC, galuhest commented on spec/spec_helper.rb
> +  def createUser(name)
fixed di fafef6457e7fcfad8f7250e1cea950fd5282791b

2018-07-04 10:37 UTC, galuhest commented on spec/item/crud_spec.rb
> +		status, id = createUser("item N")
fixed di fafef6457e7fcfad8f7250e1cea950fd5282791b

2018-07-05 06:56 UTC, yunusbahari approved these changes

2018-07-05 07:23 UTC, merged